[package]
name = "tokio-ecosystem-tests"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bytes = "1.1.0"
tokio = { version = "1.16.1", features = ["macros", "io-util", "rt-multi-thread", "test-util"] }
tokio-util = { version = "0.6.9", features = ["io"] }
tokio-stream = "0.1.8"